### ISSUE TITLE
regarding cubical type theory & canonicity

### ISSUE THREAD

**Issue by jonsterling** [type-theory/type-theory-study-group-2015#2]
I think that cubical type theory is sufficiently technical and not-yet-figured-out that it might be a bit too advanced a topic. cubical type theories as published today do not have the canonicity property, though they are a lot closer than "Book HoTT".

so far the only higher dimensional type theory which has had canonicity is Bob Harper & Dan Licata's Two Dimensional Type Theory; might be worthwhile to take a look at that in the study group, since it is a "straightforward" generalization of the Nuprl semantics with one further dimension.

(I also wouldn't call cubical type theory as "special case of HoTT w/ canonicity", since HoTT doesn't have canonicity (yet); I'd say it is a proposed higher-dimensional type theory which may come to have the canonicity property.)

**Comment by jozefg** [comment]
I'm also unaware of any resources on cubical type theory that actually make sense to people not doing research on cubical type theory. Though I would love to be surprised :)

**Comment by jonsterling** [comment]
Yeah... Even people who _are_ working on cubical type theory have told me they don't understand many of the papers that are being published about it.

**Comment by markfarrell** [comment]
I don't really understand 'cubical type theory' either,  but was, broadly speaking, impressed with Dan Licata's talk [A Cubical Infinite Dimensional Type Theory](https://www.youtube.com/watch?v=lt8JgGRw7gg) and the project [Cubical Type Theory](https://github.com/mortberg/cubicaltt) here on GitHub. I've heard about Bob Harper and Dan Licata's Two Dimensional Type Theory, but haven't really looked at it or studied it any amount of detail yet. I'd imagine, as you suggested, that might be a better place to start (when we get there). Though I would like to hear what other people think of Dan's talk and/or the Cubical Type Theory project here on GitHub - partly because I don't really understand them and hope that other people would be interested and/or can help shed some light on them! :persevere:
